### PR TITLE
Test https://github.com/jenkinsci/jenkins/pull/8426

### PR DESCRIPTION
**Pull request by daniel-beck**
Test https://github.com/jenkinsci/jenkins/pull/8426

### CODE REVIEW

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/bom/pull/2412/checks?check_run_id=16175702436 looks like it might have been caused by the label optimization PR? Unrelated to https://github.com/jenkinsci/jenkins/pull/8250…

**Comment by jglick** [comment]
https://github.com/jenkinsci/jenkins/pull/8395 that is? @Vlatombe

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/335 resolves that according to https://github.com/jenkinsci/jenkins/pull/8395#issuecomment-1691533280

**Comment by MarkEWaite** [comment]
Dependabot has submitted the pull request to use the new release of durable task plugin in the bill of materials.  Refer to 

* #2414

**Comment by jglick** [comment]
Seems everything else passed, so this can be closed?

**Pull request closed without merging**
