### PR TITLE
Add `oidc-provider`

### PR DESCRIPTION
**Pull request by jglick**
Would like to catch things like https://github.com/jenkinsci/jjwt-api-plugin/pull/88#issuecomment-2038551319 earlier.

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by basil** [comment]
> I think

[SUREFIRE-1964](https://issues.apache.org/jira/browse/SUREFIRE-1964) FTR

**Comment by jglick** [comment]
```
java.lang.AssertionError: 

Expected: an instance of io.jenkins.plugins.oidc_provider.KeysTest$ExtraProvider
     but: <io.jenkins.blueocean.rest.impl.pipeline.credential.BlueOceanCredentialsProvider@5c710bdd> is a io.jenkins.blueocean.rest.impl.pipeline.credential.BlueOceanCredentialsProvider
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.jenkins.plugins.oidc_provider.KeysTest.extraCredentialsProvider(KeysTest.java:90)
```

:eyes:

**Comment by jglick** [comment]
https://ci.jenkins.io/job/Tools/job/bom/job/PR-3094/4/testReport/io.jenkins.blueocean.rest.impl.pipeline/PipelineNodeTest/pct_blueocean_plugin_weekly___submitInputPostBlockWithParallelStages/ is pending https://github.com/jenkinsci/blueocean-plugin/pull/2555 I think, thus #3114

**Pull request merged**
