### PR TITLE
Increment subversion to 2.14.4

### PR DESCRIPTION
**Pull request by car-roll**
Repetition of #557, but this time a follow up of https://github.com/jenkinsci/subversion-plugin/pull/259

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by basil — APPROVED** [review]

**Comment by jetersen** [comment]
flaky tests 😅

**Review by bitwiseman — APPROVED** [review]

**Comment by jetersen** [comment]
@timja how do you rerun the jenkins build from the github checks api. Also the build is stuck 😭

**Comment by timja** [comment]
Just click the checks tab and re-run the Jenkins one, it’s only visible if the current check is in the failed state

**Comment by jetersen** [comment]
> Just click the checks tab and re-run the Jenkins one, it’s only visible if the current check is in the failed state

Wow that is a very well hidden button... Wonder why it is available right from the checks list in the PR...

**Comment by car-roll** [comment]
@timja is it possible to get a manual release of the BOM? Or do we need to wait or an `enhancement/bugfix/etc` PR that will kick off the auto-release?

**Pull request merged**
