### PR TITLE
Use artifact caching proxy for BOM builds

### LINKED ISSUE #1508: Use artifact proxy
Akin to https://github.com/jenkins-infra/pipeline-library/pull/502.

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR uses the artifact caching proxy for Maven builds, which should strongly decrease our JFrog Artifactory bandwidth consumption and increase builds reliability.

Note: a `skip-artifact-caching-proxy` label can be added on pull request to punctually disable it and use repo.jenkins-ci.org if needed.

Closes #1508

Ref: https://github.com/jenkins-infra/helpdesk/issues/2752 & https://github.com/jenkins-infra/pipeline-library/pull/583

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by lemeurherve** [comment]
First replay working as intended, the `aws` artifact caching proxy provider was globally disabled on ci.jenkins.io, hence the following expected message:

image

I've reactivated it and restarted a replay.

**Comment by lemeurherve** [comment]
Test OK: https://ci.jenkins.io/job/Tools/job/bom/job/PR-1741/3/console

> 18:59:15  INFO: using artifact caching proxy from 'do' provider.
> 18:59:15  [Pipeline] configFileProvider
> 18:59:15  provisioning config files...
> 18:59:15  copy managed file [DigitalOcean Artifact Caching Proxy] to file:/home/jenkins/agent/workspace/Tools_bom_PR-1741@tmp/config10916661251722156996tmp
> 18:59:16  [Pipeline] {
> 18:59:16  [Pipeline] checkout
> 18:59:43  using credential app-ci.jenkins.io
> 18:59:49  Cloning the remote Git repository
> 18:59:49  Cloning with configured refspecs honoured and without tags
> 18:59:51   > JGit fetch # timeout=10
> 19:00:15  remote: Enumerating objects
> 19:00:15  remote: Counting objects
> 19:00:15  remote: Compressing objects
> 19:00:16  Receiving objects
> 19:00:16  Resolving deltas
> 19:00:18  Updating references
> 19:00:21  Fetching without tags
> 19:00:21  Checking out Revision ac920ad88aae3c3b30dde3a36883ff8f0a6e4b7a (PR-1741)
> 19:00:21   > JGit fetch # timeout=10
> 19:00:25  Commit message: "feat: use artifact caching proxy"
> 19:00:27  [GitHub Checks] GitHub check (name: Jenkins, status: in_progress) has been published.
> 19:00:27  using credential app-ci.jenkins.io
> 19:00:27  using credential app-ci.jenkins.io
> 19:00:28  [GitCheckoutListener] Recording commits of 'git https://github.com/jenkinsci/bom.git'
> 19:00:28  [GitCheckoutListener] Found previous build 'Tools/bom/PR-1741 #2' that contains recorded Git commits
> 19:00:28  [GitCheckoutListener] -> Starting recording of new commits since 'ac920ad'
> 19:00:28  [GitCheckoutListener] -> Single parent commit found - branch is already descendant of target branch head
> 19:00:28  [GitCheckoutListener] -> Using head commit 'ac920ad' as starting point
> 19:00:28  [GitCheckoutListener] -> No new commits found
> 19:00:28  [GitCheckoutListener] -> Git commit decorator successfully obtained 'hudson.plugins.git.browser.GithubWeb@419748ae' to render commit links
> 19:00:28  [Pipeline] withEnv
> 19:00:28  [Pipeline] {
> 19:00:28  [Pipeline] sh
> 19:00:30  + bash prep.sh
> 19:00:30  ++ dirname prep.sh
> 19:00:30  + cd .
> 19:00:30  + MVN='mvn -B -ntp'
> 19:00:30  + [[ -n /home/jenkins/agent/workspace/Tools_bom_PR-1741@tmp/config10916661251722156996tmp ]]
> 19:00:30  + MVN='mvn -B -ntp -s /home/jenkins/agent/workspace/Tools_bom_PR-1741@tmp/config10916661251722156996tmp'
> 19:00:30  + mvn -B -ntp -s /home/jenkins/agent/workspace/Tools_bom_PR-1741@tmp/config10916661251722156996tmp clean install -Dset.changelist

**Comment by lemeurherve** [comment]
Reviews welcome, will put this PR out of draft as soon as the corresponding pipeline-library PR is merged, no change expected.

**Review by MarkEWaite — APPROVED** [review]
Change looks good to me.  The removed `retrieveMavenSettingsFile` was intentionally creating an empty settings.xml file.  Now we'll use the artifact caching proxy and don't need that empty settings file.

**Review by jglick — APPROVED** [review]
Thanks!

**Review by timja — APPROVED** [review]

**Comment by lemeurherve** [comment]
https://github.com/jenkins-infra/pipeline-library/pull/583 merged, I've restarted a build which successfully finished: https://ci.jenkins.io/job/Tools/job/bom/view/change-requests/job/PR-1741/6/console

Ready to merge when you want.

**Pull request merged**
