### PR TITLE
Detect overall PCT failures

### PR DESCRIPTION
**Pull request by jglick**
When PCT _compilation_ succeeded but `surefire:test` or one of its preparatory goals crashed (i.e., not just some test failures), we were silently skipping that plugin, and it seems there were several of these. Noticed in #179. At root this seems like a flaw in PCT which I am just working around here.

### CODE REVIEW

**Comment by timja** [comment]
My browser just chokes trying to look at the log, and blueocean keeps jumping to the bottom -.-

**Comment by jglick** [comment]
Do not use either of those :smile: but rather https://ci.jenkins.io/job/Tools/job/bom/job/PR-277/1/execution/node/3704/log/ https://ci.jenkins.io/job/Tools/job/bom/job/PR-277/1/execution/node/1768/log/ https://ci.jenkins.io/job/Tools/job/bom/job/PR-277/1/execution/node/5965/log/

**Comment by raul-arabaolaza** [comment]
@jglick LGTM, I can confirm that is an issue that we have solved in other places in similar ways

**Comment by jetersen** [comment]
@jglick I'd like to understand how to get to those partial logs.

**Comment by jglick** [comment]
> how to get to those partial logs

We could `archiveArtifacts` them I suppose, or try to inline them into a `CDATA` section in the synthetic test report, or you can just look at the build log as in https://github.com/jenkinsci/bom/pull/277#issuecomment-661331230.

**Comment by jetersen** [comment]
@jglick I was more referring on how to navigate to them in the Jenkins UI

**Comment by jglick** [comment]
Go to **Pipeline Steps**, search for the branch corresponding to the test failure, look for the `… && bash pct.sh` step, and click the terminal icon next to it.

**Comment by bitwiseman** [comment]
@jglick @oleg-nenashev 

So, now we have three failures.  Looking at https://ci.jenkins.io/job/Tools/job/bom/job/PR-277/3/ here are the logs pulled out:

- pct-matrix-project-2.235.x - https://ci.jenkins.io/job/Tools/job/bom/job/PR-277/3/execution/node/2397/log/
- pct-matrix-project-2.176.x - https://ci.jenkins.io/job/Tools/job/bom/job/PR-277/3/execution/node/8075/log/
- pct-ssh-credentials-2.176.x - https://ci.jenkins.io/job/Tools/job/bom/job/PR-277/3/execution/node/8561/log/

I'm not even sure how to read the failures. When this kind of failure occurs do we want/need to rerun with `mvn -X` ?

**Comment by timja** [comment]
the ssh-credentials one looks like a straightforward one to do with the jcasc test harness

**Comment by jglick** [comment]
> do we want/need to rerun with `mvn -X` ?

You can run PCT for one LTS line and plugin locally quite easily: https://github.com/jenkinsci/bom/#pct

The `matrix-project` one looks simple enough: just needs to be updated to a new parent POM to pick up https://github.com/jenkinsci/jenkins-test-harness/pull/79.

**Comment by jglick** [comment]
…which is blocked in #274 on some weirdness I have not dealt with yet: https://github.com/jenkinsci/bom/pull/251#issuecomment-645012427

**Comment by jglick** [comment]
The `ssh-credentials` issue may be because in #110 we stopped updating this plugin. Running `git bisect` now…

**Comment by timja** [comment]
@jglick https://github.com/jenkinsci/bom/pull/287

**Comment by jglick** [comment]
Flakes?

**Pull request merged**
