### PR TITLE
Test project configure page

### PR DESCRIPTION
**Pull request by timja**
https://github.com/jenkinsci/jenkins/pull/6485

### CODE REVIEW

**Comment by janfaracik** [comment]
Don't suppose you know if this is one of those hard to debug errors due to using some new JS syntax? Nothing is particularly standing out in the JS

**Comment by timja** [comment]
> Don't suppose you know if this is one of those hard to debug errors due to using some new JS syntax? Nothing is particularly standing out in the JS

I expect some expected element isn't being found which is breaking it, not sure why, haven't had a chance to look

**Comment by basil** [comment]
The `ReadManifestStepTest` failures were caused by a minor incompatibility introduced in https://github.com/jenkinsci/remoting/pull/532 combined with the lack of timely merge and release of https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/143. I have worked around the problem in #1145 by excluding the test class.

**Comment by janfaracik** [comment]
Finally had the time to have a dabble in this and it seems that the fix should be to update the test harness, `htmlunit 2.59.0` and below give the `Cannot call method "addEventListener" of null` error, versions above that don't. I'll open some PRs to get the repos up to date.

**Comment by timja** [comment]
Passing now, only matrix-auth unreleased, we can exclude the tests if it doesn't get released in time, it's a tests only issue

**Pull request closed without merging**
