### PR TITLE
Update jacoco from 3.3.4 to 3.3.5 and remove Java 21 workaround

### PR DESCRIPTION
**Pull request by NotMyFault**
Fixes https://github.com/jenkinsci/bom/issues/2383

### CODE REVIEW

**Comment by jglick** [comment]
```
Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.49:validate-hpi (default-validate-hpi) on project sample: Dependency org.jenkins-ci.plugins:jacoco:jar:3.3.5 requires Jenkins 2.401.3 or higher.
```

**Comment by MarkEWaite** [comment]
Since the google-compute-engine-plugin 3.3.5 requires Jenkins 2.401.3 or newer, I believe the workaround will still be needed until we remove the 2.387.x line from the plugin bill of materials.  As a cost reduction effort, that removal will probably be proposed when it is time to add the 2.426.x line.

I see the failure when I run this pull request locally with the command (after configuring to use Java 21):

```bash
$ java -version
java version "21" 2023-09-19 LTS
Java(TM) SE Runtime Environment (build 21+35-LTS-2513)
Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)
$ LINE=2.387.x PLUGINS=jacoco bash local-test.sh
...
[ERROR] Errors:
...
[ERROR]   JacocoPublisherTest.<init>:50 » IllegalArgument Could not create type
[ERROR] Tests run: 203, Failures: 0, Errors: 17, Skipped: 8
```

**Comment by NotMyFault** [comment]
Am I missing something, where are the failures from the google-compute-engine-plugin are coming from?

I thought I've removed the workaround for the jacoco plugin, which now supports Java 21.

**Comment by MarkEWaite** [comment]
> Am I missing something, where are the failures from the google-compute-engine-plugin are coming from?
> 
> I thought I've removed the workaround for the jacoco plugin, which now supports Java 21.

I think that my earlier comment was completely off target.  Sorry about that!

The test failures in google compute engine and google storage engine are unrelated to this change.  I think that they are failures that will be visible on the master branch when we next run full tests on the master branch.

The failures that I was reporting with the jacoco plugin are because I was using an invalid local configuration.  I was testing the 2.387.x line with Java 21.  That's not what is done in the Jenkinsfile.  It tests the 2.387.x line with Java 11.  Java 21 is testing on the weekly line.  When I run the jacoco tests locally with Java 11, they pass for me just as they pass on ci.jenkins.io.

Thanks for detecting the issue on the master branch.  That will give me time to understand and resolve the issue before a new release of the plugin bill of materials tomorrow.

**Comment by MarkEWaite** [comment]
I've confirmed that I can see the issue on the master branch with the following command line (using Java 21):

```bash
LINE=weekly PLUGINS=google-storage-plugin TEST=ClientFactoryTest bash local-test.sh
```

**Comment by MarkEWaite** [comment]
Reverting the upgrade of the google oauth plugin fixes the failing test on the master branch.  6407824d0f8432c5f373aa158fd60cd08a3d3e3c will need to be reverted.

**Comment by MarkEWaite** [comment]
I've submitted the revert as

* #2567

**Pull request merged**
