### PR TITLE
Test Guice 6.0 upgrade in Jenkins core

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Test Guice 6.0 upgrade in Jenkins core

https://github.com/jenkinsci/jenkins/pull/7990 proposes to upgrade to Guice 6.0 in Jenkins core as part of the transition away from the `javax.*` bindings to the `jakarta.*` bindings.

See the [Guice 6.0.0 changelog](https://github.com/google/guice/wiki/Guice600) for details of the Guice 6.0.0 changes.

### Testing done

Confirmed that `mvn --pl sample-plugin -DforkCount=1C verify` passes.  Will rely on ci.jenkins.io to perform more testing.

### Submitter checklist

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes

### CODE REVIEW

**Comment by NotMyFault** [comment]
Thanks for creating the PR, Mark.

The couple of failures are unrelated to the guice upgrade because I can replicate the failures by testing the matrix-project plugin (`mvn clean verify -Dtest=hudson.matrix.MatrixProjectTest`) against `2.405-rc33688.8f06b_f4c7fe8`, the incremental of the latest master revision of core.

**Comment by MarkEWaite** [comment]
Thanks for the analysis @NotMyFault .  I've run some further tests and narrowed the change between

* Jenkins build 4910 fails
* Jenkins build 4902 passes

Further narrowing to a specific commit in that range will require that I checkout Jenkins and build it locally.

**Comment by MarkEWaite** [comment]
Bisect indicates that the matrix-project tests first fail with https://github.com/jenkinsci/jenkins/commit/9d6f0743ba58ad51ffa84e46c34af0b5c788ad5b that is part of:

* https://github.com/jenkinsci/jenkins/pull/7911

I'll perform some more diagnosis and may then ask for help from @mawinter69

**Comment by MarkEWaite** [comment]
Closing this pull request.  It showed no issues that are specific to the Guice 6.0 upgrade.

**Pull request closed without merging**
