### PR TITLE
Add gson-api plugin to bom

### PR DESCRIPTION
**Pull request by jonesbusy**
Not sure about the order. Should we fist replace dependency by the api plugin or first include it to bom ?

### Testing done

```
PLUGINS=gson-api bash local-test.sh 
```

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by timja — APPROVED** [review]
either works

**Comment by MarkEWaite** [comment]
Thanks for the pull request @jonesbusy .  I'm borrowing to run a larger test as part of the [Artifactory brownout](https://groups.google.com/g/jenkinsci-dev/c/Jn_4U-KQUqg/m/N5i6VH7_AAAJ) .  I've added the `weekly-test` label so that it will run a wider range of tests on the pull request while we're in the brownout period.  Brownout will end in about 45 minutes

**Review by MarkEWaite — APPROVED** [review]
Thanks very much.  Passed the larger test

**Comment by basil** [comment]
@jonesbusy Very nice! Thanks a lot for this contribution. If you're interested, it would be nice to get rid of GSON from these plugins:

```
./git-client/WEB-INF/lib/gson-2.10.1.jar
./google-compute-engine/WEB-INF/lib/gson-2.9.0.jar
./google-kubernetes-engine/WEB-INF/lib/gson-2.10.1.jar
./google-oauth-plugin/WEB-INF/lib/gson-2.9.1.jar
./google-storage-plugin/WEB-INF/lib/gson-2.10.1.jar
./trilead-api/WEB-INF/lib/gson-2.8.9.jar
```

If you aren't interested, then that is quite alright and I will file some Jira tickets against those individual plugins so that we can track the long-term effort to consolidate this library.

Thanks again.

**Comment by basil** [comment]
Unrelated to this PR, but another top offender is Joda Time, which has embedded itself in many places:

```
aws-java-sdk-minimal/WEB-INF/lib/joda-time-2.8.1.jar
dockerhub-notification/WEB-INF/lib/joda-time-2.10.14.jar
google-metadata-plugin/WEB-INF/lib/joda-time-2.12.5.jar
google-oauth-plugin/WEB-INF/lib/joda-time-2.12.5.jar
google-storage-plugin/WEB-INF/lib/joda-time-2.12.5.jar
handy-uri-templates-2-api/WEB-INF/lib/joda-time-2.10.2.jar
pipeline-model-api/WEB-INF/lib/joda-time-2.10.5.jar
saml/WEB-INF/lib/joda-time-2.11.0.jar
```

`org.json:json` would be nice to turn into a library, especially because old versions have a weird license:

```
configuration-as-code/WEB-INF/lib/json-20231013.jar
jackson2-api/WEB-INF/lib/json-20231013.jar
```

The pair of `json-path`/`json-smart` also crops up now and again:

```
google-kubernetes-engine/WEB-INF/lib/json-path-2.8.0.jar
google-kubernetes-engine/WEB-INF/lib/json-smart-2.4.10.jar
token-macro/WEB-INF/lib/json-path-2.8.0.jar
token-macro/WEB-INF/lib/json-smart-2.4.10.jar
```

**Comment by jonesbusy** [comment]
@basil  Thanks, yea I will do the replacement step by step starting with existing API plugins in the bom. I started with the 'git-client' for now

I can take the point of `org.json:json` and `joda-time` it's ok for me.

**Comment by jonesbusy** [comment]
@basil Following PR have been open (some merged / releases already)

https://github.com/jenkinsci/google-kubernetes-engine-plugin/pull/363
https://github.com/jenkinsci/token-macro-plugin/pull/204
https://github.com/jenkinsci/saml-plugin/pull/389
https://github.com/jenkinsci/aws-java-sdk-plugin/pull/1159
https://github.com/jenkinsci/handy-uri-templates-2-api-plugin/pull/29
https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/684
https://github.com/jenkinsci/jackson2-api-plugin/pull/228
https://github.com/jenkinsci/trilead-api-plugin/pull/131
https://github.com/jenkinsci/configuration-as-code-plugin/pull/2431
https://github.com/jenkinsci/dockerhub-notification-plugin/pull/45

**Comment by basil** [comment]
Very nice!

**Comment by basil** [comment]
I have filed the following tickets to track the updating of `analysis-model-api` and `warnings-ng`:

- https://issues.jenkins.io/browse/JENKINS-72493
- https://issues.jenkins.io/browse/JENKINS-72494
- https://issues.jenkins.io/browse/JENKINS-72495
- https://issues.jenkins.io/browse/JENKINS-72496
- https://issues.jenkins.io/browse/JENKINS-72497

**Comment by basil** [comment]
I have filed the following tickets to track the updating of `google-compute-engine`, `google-oauth`, and `google-storage`:

- https://issues.jenkins.io/browse/JENKINS-72857
- https://issues.jenkins.io/browse/JENKINS-72858
- https://issues.jenkins.io/browse/JENKINS-72859

I have filed the following tickets to track the updating of `google-metadata`, `google-oauth`, and `google-storage`:

- https://github.com/jenkinsci/google-metadata-plugin/issues/65
- https://issues.jenkins.io/browse/JENKINS-72860
- https://issues.jenkins.io/browse/JENKINS-72861

**Pull request merged**
