### PR TITLE
Removed 2.138.x line

### PR DESCRIPTION
**Pull request by jglick**
Now that 2.204.x is published, this line no longer has its own update center, so it is increasingly pointless to use as a baseline. Also there are a lot of troublesome failures.

### CODE REVIEW

**Comment by casz** [comment]
I assume those will follow once 2.138 is removed ;)

**Comment by jglick** [comment]
`git-client` failures, which I have also seen elsewhere. Will try to track them down. Complicated because #132 has _other_ failures.

**Comment by jglick** [comment]
> Will try to track them down.

https://github.com/jenkinsci/git-client-plugin/pull/478#issuecomment-570788273

**Comment by jglick** [comment]
Blocked, along with all other PRs in this repository, by #148.

**Pull request merged**
