### PR TITLE
Add commons-math3-api plugin

### PR DESCRIPTION
**Pull request by jonesbusy**
Add commons-math3-api plugin

### Testing done

```
PLUGINS=commons-math3-api TEST=InjectedTest bash local-test.sh
```

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by timja** [comment]
FWIW this has been removed from junit, are there consumers that would benefit from this?

**Comment by jonesbusy** [comment]
Found some of them with compile scope dependency https://github.com/search?q=org%3Ajenkinsci+%22commons-math3%22&type=code&p=2

Most need refresh but a few looks still active.

Not sure if it deserve bom to have version managed at least

**Comment by timja** [comment]
2 or 3 look somewhat active, 1 of them currently uses bom.

I think we can do this, anyone else got another opinion?

**Comment by basil** [comment]
I don't see a problem with this as long as weekly tests are passing, though as noted above there is not much of a need for this in the ecosystem at present.

**Pull request merged**
