### PR TITLE
Add 2.462.x release line, remove 2.426.x

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Add 2.462.x line, remove 2.426.x line

- Add 2.462.x release line
- Remove 2.426.x line
- Replace 2.426 with 2.440 in documentation
- Use 2.452.3 instead of 2.452.1 as 2.452.x Jenkins version
- Document the final 2.426.x BOM version

Fixes https://github.com/jenkinsci/bom/issues/3301

### Testing done

Confirmed that `mvn clean verify` and `PLUGINS=structs,mailer TEST=InjectedTest bash local-test.sh` pass locally.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by gounthar — APPROVED** [review]

**Review by jglick — COMMENTED** [review]
Did you forget to update https://github.com/jenkinsci/bom/blob/2dd9d953f51e33f1a18777491c785c57507bb9a8/bom-2.452.x/pom.xml#L20?

**Comment by MarkEWaite** [comment]
> Did you forget to update
> 
> https://github.com/jenkinsci/bom/blob/2dd9d953f51e33f1a18777491c785c57507bb9a8/bom-2.452.x/pom.xml#L20
> 
> ?

Thanks very much for catching that mistake!  Corrected as 99a27d3ae23d7a542db105494ed30aae155bc797

**Review by jglick — APPROVED** [review]

**Comment by jglick** [comment]
Passing now @MarkEWaite; did you plan to merge & release?

**Comment by MarkEWaite** [comment]
> Passing now @MarkEWaite; did you plan to merge & release?

Thanks for asking.  I thought that we'd run the weekly release tomorrow without this change and then merge it and release it at the end of next week.  The first release candidate of 2.462.1 will be available Wednesday then the the first BOM release with the 2.462.x profile will be available on Friday or Saturday.

Let me know if there is a specific benefit to merging sooner.  I'm happy to merge sooner, but didn't want to drop the 2.426.x line until after the 2.462.1 RC was available.

**Comment by MarkEWaite** [comment]
I'm intentionally leaving the conflict in this pull request until the next time that I want to perform a full test of the latest changes on the master branch.

**Comment by MarkEWaite** [comment]
> I'm intentionally leaving the conflict in this pull request until the next time that I want to perform a full test of the latest changes on the master branch.

I've resolved the conflict to test the merge of the ssh-credentials 342.x release that arrived in:

* #3402 

Full test has started and should confirm that change is passing tests.  Before submitting the most recent change, I confirmed passing results for:

```bash
$ mvn clean verify
$ PLUGINS=ssh-credentials TEST=InjectedTest bash local-test.sh
```

Once full tests pass, I plan to merge this.

**Pull request merged**
