### PR TITLE
Add jackson2-api

### PR DESCRIPTION
**Pull request by chriskilding**

### CODE REVIEW

**Comment by chriskilding** [comment]
Using 2.11.0 for now, because 2.11.1 bundles jackson-dataformat-yaml which conflicts with a different plugin that also includes it.

**Comment by chriskilding** [comment]
We are limited by past BOMs up to 2.204, which include CasC test harness 1.36, which in turn needs Jackson 2.10.2.

This probably means we can't progress with Jackson 2.11.x while those Jenkins versions are still supported, so will wind this PR back to 2.10.2.

**Comment by jetersen** [comment]
Simply do the same thing we do for JCasC 😅

**Comment by jetersen** [comment]
Oh it's just the sample plugin, I would simply exclude the databinding from the test-harness.

**Comment by jetersen** [comment]
The JCasC test harness can definitely use the BOM and same jackson version to avoid conflicts 👍

I think this is ready for merge?

**Comment by timja** [comment]
Need to resolve https://github.com/jenkinsci/bom/pull/277 first AFAIK

**Comment by jetersen** [comment]
The test passed though @timja ? 😕

**Pull request merged**
