### PR TITLE
Test plugins on java 11

### PR DESCRIPTION
**Pull request by timja**
Just seeing what it's like

### CODE REVIEW

**Comment by timja** [comment]
@jglick any idea why the git plugin resolved token-macro 2.13?

`[2021-02-06T16:04:10.657Z] [INFO]    org.jenkins-ci.plugins:token-macro:jar:2.13:compile (optional)  -- module token.macro (auto)`

**Comment by jglick** [comment]
Not offhand. Something different than Java 8 behavior?

**Comment by timja** [comment]
> Not offhand. Something different than Java 8 behavior?

I think so, need more time to dig into it. Some

**Comment by basil** [comment]
`com.cloudbees.hudson.plugins.folder.FolderTest#shouldProperlyPersistFolderPropertiesOnMultipleReloads` seems to be failing in PCT on Java 11 (I can reproduce locally). The same test passes in Java 11 outside of PCT.

**Pull request closed without merging**
