### PR TITLE
Add 2.222.x & 2.204.x, remove 2.150.x

### PR DESCRIPTION
**Pull request by jglick**
#214 continued

### CODE REVIEW

**Comment by jetersen** [comment]
@jglick fyi you can always just push into the same PR, no need to create a new PR as you have maintainer rights usually unless the author chose not to give you access.

**Comment by jglick** [comment]
A quick attempt did not work. Anyway I find it clearer to create a separate PR to indicate what _I_ think should be merged, so I am not misrepresenting what @timja meant.

**Comment by jetersen** [comment]
commit history clearly shows that 🤔

github cli or hub can help with setting up the correct remotes.

`hub pr checkout <number>`
`gh pr checkout <number>`

**Comment by jglick** [comment]
> `gh pr checkout <number>`

Did that, and could not push to the resulting branch. :shrug:

**Comment by jetersen** [comment]
(╯▔皿▔)╯

**Pull request merged**
