### PR TITLE
debug: force DigitalOcean usage with its own artifact-caching-proxy

### PR DESCRIPTION
**Pull request by dduportal**
This PR is a debug test run around https://github.com/jenkins-infra/helpdesk/issues/3481

No need to review or merge it.

### CODE REVIEW

**Comment by lemeurherve** [comment]
> [ERROR] Unresolveable build extension: Plugin org.jenkins-ci.tools:maven-hpi-plugin:3.38 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.codehaus.groovy:groovy-all:jar:2.4.21 (absent): Could not transfer artifact org.codehaus.groovy:groovy-all:jar:2.4.21 from/to do-proxy (https://repo.do.jenkins.io/public/): Premature end of Content-Length delimited message body (expected: 7,203,079; received: 2,615,877)

**Comment by dduportal** [comment]
Yup, so despite using Maven 3.9.1, the error is still present on DigitalOcean.

Next step: https://github.com/jenkins-infra/helm-charts/pull/471

**Comment by dduportal** [comment]
Build number 6 was forced to DigitalOcean (label `doks`), has the changes from #1955 , but no artifact caching proxy, as a "control build". It was successful in ~ 1h46 (with only 50 parallel agents in DigitalOcean and no concurent build).

Retrying with the artifact caching proxy to see if the download issue are present or not.

Please note the differences with the initial problem described in https://github.com/jenkins-infra/helpdesk/issues/3481:

-  Only 50 agent in DOKS instead of 150 originally because of  https://github.com/jenkins-infra/helpdesk/issues/3487
- Nginx tuning has been applied to the ACP system: https://github.com/jenkins-infra/kubernetes-management/pull/3786

**Comment by dduportal** [comment]
I can't reproduce the ACP error with this setup. 

Can you confirm my assesment is correct @basil @lemeurherve ?

**Comment by MarkEWaite** [comment]
I've launched a build of [upgrade 2.399 to 2.400 in bom](https://ci.jenkins.io/job/Tools/job/bom/view/change-requests/job/PR-1959/) with ACP enabled.  Running now

**Comment by basil** [comment]
I added

```groovy
diff --git a/Jenkinsfile b/Jenkinsfile
index 37b81020..43645de8 100644
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@ -67,6 +67,7 @@ for (int i = 0; i < splits.size(); i++) {
             image.inside('-v /var/run/docker.sock:/var/run/docker.sock --shm-size 2g') {
               def exclusions = splits.get(index).join('\n')
               writeFile file: 'excludes.txt', text: exclusions
+              infra.withArtifactCachingProxy {
                 realtimeJUnit(
                   testResults: 'target/surefire-reports/TEST-*.xml',
                   testDataPublishers: [[$class: 'AttachmentPublisher']],
@@ -91,6 +92,7 @@ for (int i = 0; i < splits.size(); i++) {
         }
       }
     }
+  }
 }
 parallel branches
 infra.maybePublishIncrementals()
```

to ATH in https://github.com/jenkinsci/acceptance-test-harness/pull/1107 and reproduced one of the failures that I had previously reported on the first try.

https://ci.jenkins.io/job/Core/job/acceptance-test-harness/view/change-requests/job/PR-1107/2/execution/node/439/log/

**Comment by dduportal** [comment]
> I added
> 
> ```groovy
> diff --git a/Jenkinsfile b/Jenkinsfile
> index 37b81020..43645de8 100644
> --- a/Jenkinsfile
> +++ b/Jenkinsfile
> @@ -67,6 +67,7 @@ for (int i = 0; i < splits.size(); i++) {
>              image.inside('-v /var/run/docker.sock:/var/run/docker.sock --shm-size 2g') {
>                def exclusions = splits.get(index).join('\n')
>                writeFile file: 'excludes.txt', text: exclusions
> +              infra.withArtifactCachingProxy {
>                  realtimeJUnit(
>                    testResults: 'target/surefire-reports/TEST-*.xml',
>                    testDataPublishers: [[$class: 'AttachmentPublisher']],
> @@ -91,6 +92,7 @@ for (int i = 0; i < splits.size(); i++) {
>          }
>        }
>      }
> +  }
>  }
>  parallel branches
>  infra.maybePublishIncrementals()
> ```
> 
> to ATH in [jenkinsci/acceptance-test-harness#1107](https://github.com/jenkinsci/acceptance-test-harness/pull/1107) and reproduced one of the failures that I had previously reported on the first try.
> 
> https://ci.jenkins.io/job/Core/job/acceptance-test-harness/view/change-requests/job/PR-1107/2/execution/node/439/log/

Thanks for checking, but we are not interested in the activation of ACP for the ATH (yet), because it is another cause of failure than the BOM (different instance of ACP, different cloud, different agent, different network).

**Comment by basil** [comment]
Then I think it would be interesting to try an ATH run with ACP and the desired cloud to see how it compares with BOM. It is a bit of a stress test but not as much of a stress test as BOM so it might be more manageable.

**Comment by dduportal** [comment]
> Then I think it would be interesting to try an ATH run with ACP and the desired cloud to see how it compares with BOM. It is a bit of a stress test but not as much of a stress test as BOM so it might be more manageable.

The main issue with this use case (that we would have wanted to try) is the "cross-cloud" bandwidth.
ATH runs in virtual machine agents because of the Docker requirement, and ci.jenkins.io is only able to spaws VM agents in Azure (and used to in AWS EC2 but it is disabled for now and might not come back due to the costs).
Forcing the use of DigitalOcean ACP with Azure agents (for this ACP) test will results in data being sent from a DigitalOcean designed private service to Azure (not mentioning the latency and slowness).


But we can absolutely "ramp-up" the stress to find the threshold from which DigitalOcean's ACP start to fail using the BOM: we have a hard limit on how much container agents can run at the same time in the `doks` cluster (it is currently 50): that is the reason I'm asking for a second view: is the BOM, in this current state (e.g. max 50 simultaneous DigitalOcean agents using the DigitalOcean ACP) able to reproduce the issue.

- If yes, then gotta diagnose
- If no, then we can try increasing

Please note that, with the current credit consumption in DigitalOcean (except March which was unexpectly high), this "50" container limit might not be increased again (March was a first try at 150 max).
=> Eventually, BOM builds could be restricted to a dedicated AWS (which we could optimize only for bom perfs/costs).

**Comment by dduportal** [comment]
Closing in favor of #1969

**Pull request closed without merging**
