### PR TITLE
Add 2.452.x line, remove 2.414.x line

### PR DESCRIPTION
**Pull request by NotMyFault**
Signed-off-by: Alexander Brandes <mc.cache@web.de>

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by jglick** [comment]
Do you plan to release this soon? Would be helpful for the likes of https://github.com/jenkinsci/workflow-job-plugin/pull/428.

**Comment by MarkEWaite** [comment]
> Do you plan to release this soon? Would be helpful for the likes of [jenkinsci/workflow-job-plugin#428](https://github.com/jenkinsci/workflow-job-plugin/pull/428).

I think that we are very near a new release, once the addition of pipeline graph view is complete.

**Comment by basil** [comment]
@jenkinsci/bom-developers :eyes:

**Pull request merged**
