### PR TITLE
Bump pipeline-model-definition-plugin to v1.9.0

### PR DESCRIPTION
**Pull request by bitwiseman**
Updated pipeline-model-definition with a number dependency updates, test fixes, and tweaks.

https://github.com/jenkinsci/pipeline-model-definition-plugin/releases/tag/pipeline-model-definition-1.9.0

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by basil** [comment]
New baseline, need to exclude from the 2.222.x line.

**Comment by timja** [comment]
Will be resolved by https://github.com/jenkinsci/bom/pull/587

**Comment by timja** [comment]
Same issue as in https://github.com/jenkinsci/bom/pull/587#issuecomment-889035745

**Comment by basil** [comment]
It doesn't look like `pipeline-model-definition` 1.9.0 works at all on 2.277. I filed [JENKINS-66247](https://issues.jenkins.io/browse/JENKINS-66247) to track this. In the meantime, let's upgrade `pipeline-model-definition` to 1.9.0 only on the 2.289.x and later BOM lines pending the resolution of JENKINS-66247.

**Comment by basil** [comment]
I'm going ahead with the merge of this PR, as I can't reproduce any of the CI failures locally with `LINE=2.289.x PLUGINS=pipeline-model-definition TEST=InjectedTest,org.jenkinsci.plugins.pipeline.modeldefinition.actions.RestartDeclarativePipelineActionTest,org.jenkinsci.plugins.pipeline.modeldefinition.cli.DeclarativeLinterCommandTest,org.jenkinsci.plugins.pipeline.modeldefinition.endpoints.ErrorsEndpointOpsTest,org.jenkinsci.plugins.pipeline.modeldefinition.endpoints.ModelConverterActionStepsTest,org.jenkinsci.plugins.pipeline.modeldefinition.endpoints.ModelConverterActionTest,org.jenkinsci.plugins.pipeline.modeldefinition.endpoints.SuccessfulEndpointOpsTest,org.jenkinsci.plugins.pipeline.modeldefinition.MatrixTest,org.jenkinsci.plugins.pipeline.modeldefinition.WhenStageTest bash local-test.sh`.

**Comment by jglick** [comment]
@basil remember to label PRs before merging, and this drives behavior of Release Drafter and thus the decision to create a release or not.

**Comment by jglick** [comment]
(You can add a label after the effect, but R.D. will only update the release draft after the _next_ PR has been merged, or someone otherwise pushes to `master`.)

**Pull request merged**
