### PR TITLE
Try matrix-auth 3.1.7-rc416.ad0d7cac657a

### PR DESCRIPTION
**Pull request by daniel-beck**
Downstream of https://github.com/jenkinsci/matrix-auth-plugin/pull/136

### CODE REVIEW

**Comment by daniel-beck** [comment]
Docs at https://github.com/jenkinsci/bom#incrementals claim this is supposed to work?

**Comment by daniel-beck** [comment]
> The deployment happens as the last step of the Pipeline and the Pipeline job has not yet completed.

Unsure what you mean. https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/matrix-auth/3.1.7-rc416.ad0d7cac657a/ has been deployed an hour ago. 5 minutes later I filed this PR.

**Comment by MarkEWaite** [comment]
I can't resolve that version of matrix-auth locally either.  I used the git plugin as a test and added an incremental version of the git client, confirmed that it would build.  I added a dependency on matrix-auth plugin with the default version and confirmed the git plugin compiles as well.  I added a dependency on matrix-auth plugin 3.1.7-rc416.ad0d7cac657a and maven reports that it cannot resolve the dependency.

I'm not sure what it is, but as far as I can tell, it is not specific to the bill of materials and is not specific to the artifact caching proxy.

**Comment by MarkEWaite** [comment]
There was an issue somewhere with SHA-1 strings that end in the letter `a` or the letter `b` and their being misinterpreted by something, but I thought that was specific to dependabot, not anything related to maven.

**Comment by MarkEWaite** [comment]
@daniel-beck are you able to reference that incremental artifact from the pom file of another project?

**Comment by daniel-beck** [comment]
Interestingly, this new PR build seems to have passed the initial `sample-plugin` error.

**Comment by MarkEWaite** [comment]
> Interestingly, this new PR build seems to have passed the initial `sample-plugin` error.

If that's the case, then it may be the artifact caching proxy.  I added the `skip-artifact-caching-proxy` label to the pull request earlier before the close and reopen.

However, I still can't explain why I can locally resolve the matrix-auth version provided by the plugin bom and the matrix-auth incremental 3.1.7-rc415.1723c7a76490 from the master branch, but cannot resolve the matrix-auth incremental from 3.1.7-3.1.7-rc416.ad0d7cac657a from the PR-136 build.

**Comment by MarkEWaite** [comment]
> However, I still can't explain why I can locally resolve the matrix-auth version provided by the plugin bom and the matrix-auth incremental 3.1.7-rc415.1723c7a76490 from the master branch, but cannot resolve the matrix-auth incremental 3.1.7-rc416.ad0d7cac657a from the PR-136 build.

I missed the maven output that warned me that it had cached the earlier lookup failure.  When I ran `mvn -U clean -DskipTests verify` it downloaded the 3.1.7-rc416.ad0d7cac657a incremental dependency from PR-136.

As Daniel has told me before, "caches be caching"...

**Review by basil — APPROVED** [review]
I tested this locally with my recent `maven-hpi-plugin` changes in PCT and it works fine. Confirming this is sufficient to unblock me.

**Comment by basil** [comment]
> @basil Why did you abort the CI build?

Last night a few BOM builds were stuck after a controller restart, so I aborted some of them to allow at least one of them (`workflow-job`) to succeed and get auto-merged. In general this repository and ci.jenkins.io appears to be in a pretty bad state right now.

In any case, I wouldn't wait for this PR to go green before merging and releasing your `matrix-auth` changes, especially because they are needed in order to adopt the latest version of PCT in this repository. I tested this PR locally with `PLUGINS=matrix-auth bash local-test.sh` and it works just fine.

**Comment by basil** [comment]
[Build is green](https://ci.jenkins.io/blue/organizations/jenkins/Tools%2Fbom/detail/PR-1911/4/)

**Comment by basil** [comment]
> So what's the root cause?

I don't know Daniel, as I have told you several times I have not investigated this deeply compared to other priorities. This experiment definitely helps. Using `RealJenkinsRule` in more places is always a good idea and would have caught https://github.com/jenkinsci/configuration-as-code-plugin/issues/2235 and https://github.com/jenkinsci/configuration-as-code-plugin/issues/2236 I think.

**Pull request closed without merging**
