### PR TITLE
Remove 2.375.x support

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Remove 2.375.x support

Many of the plugin versions managed by the plugin bill of materials have been updated to require Jenkins 2.387.1 or newer.  Those plugins include:

* https://plugins.jenkins.io/bootstrap5-api/ - Bootstrap 5 API
* https://plugins.jenkins.io/branch-api/ - Branch API
* https://plugins.jenkins.io/checks-api - GitHub checks API
* https://plugins.jenkins.io/configuration-as-code - Configuration as code
* https://plugins.jenkins.io/credentials/ - Credentials
* https://plugins.jenkins.io/custom-folder-icon - Configuration as code
* https://plugins.jenkins.io/data-tables-api/ - Data tables API
* https://plugins.jenkins.io/echarts-api/ - echarts API
* https://plugins.jenkins.io/font-awesome-api/ - Font awesome API
* https://plugins.jenkins.io/forensics-api/ - Forensics API
* https://plugins.jenkins.io/git-client/ - Git client
* https://plugins.jenkins.io/git/ - Git
* https://plugins.jenkins.io/junit-attachments/ - JUnit attachments
* https://plugins.jenkins.io/junit/ - JUnit
* https://plugins.jenkins.io/lockable-resources/ - Lockable resources
* https://plugins.jenkins.io/pipeline-build-step/ - Pipeline: build step
* https://plugins.jenkins.io/pipeline-model-api/  - Pipeline: declarative
* https://plugins.jenkins.io/pipeline-model-definition/  - Pipeline: declarative
* https://plugins.jenkins.io/pipeline-model-extensions/  - Pipeline: declarative
* https://plugins.jenkins.io/pipeline-stage-tags-metadata/  - Pipeline: declarative
* https://plugins.jenkins.io/plugin-util-api - Plugin utilities API
* https://plugins.jenkins.io/workflow-cps/ - Pipeline: Groovy
* https://plugins.jenkins.io/workflow-multibranch/ - Pipeline: Multibranch
* https://plugins.jenkins.io/workflow-scm-step/ - Pipeline: SCM step

Over 15% of the plugins in the bill of materials already require a core version newer than 2.375.4.

There are relatively few plugins that require Jenkins 2.375.x.

The benefits of testing for compatibility with Jenkins 2.375.x decrease each time a plugin requires a version newer than 2.375.x.

The last two releases of the plugin bill of materials included no plugin version changes in the bom-2.375.x set.  One plugin version was pinned to 2.375.x, and multiple maven plugins were updated, but no plugin versions were updated.

Rather than continuing to add more pinned plugins for Jenkins 2.375.x compatibility, let's stop 2.375.x plugin bill of materials updates and limit updates to 2.387.x, 2.401.x, and weekly.

Users of previous bill of materials releases can continue to use them, but new releases will only cover 2.387.x and 2.401.x.  changes

### Testing done

* `mvn clean --pl sample-plugin -P 2.387.x verify`
* `mvn clean --pl sample-plugin -P 2.401.x verify`
* `mvn clean --pl sample-plugin            verify`

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by jglick — APPROVED** [review]

**Comment by jglick** [comment]
@MarkEWaite are you planning to release this? https://github.com/jenkinsci/bom/runs/14576031250

**Comment by MarkEWaite** [comment]
> @MarkEWaite are you planning to release this? https://github.com/jenkinsci/bom/runs/14576031250

I was planning to release it at the end of the week.  I'd like to include two additional changes in the next release of the plugin BOM:

* #2189 
* #2220 

Does it need to be released sooner than the end of the week?

**Comment by jglick** [comment]
Of course not, just checking that you had not forgotten that release on matching labels is no longer automatic.

**Comment by jglick** [comment]
https://groups.google.com/g/jenkinsci-dev/c/H8lfEx6cBBc/m/Rmu-f_LrAwAJ FTR (just saw this)

**Pull request merged**
