### PR TITLE
Revert data-tables-api, echarts-api, and prism-api

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Revert data-tables-api, echarts-api, and prism-api

Automated test detection with JUnit 5 [fails in test execution](https://ci.jenkins.io/job/Tools/job/bom/job/PR-2679/1/pipeline-console/?selected-node=284).  The problem is visible from the command line with the commands:

```bash
$ java -version
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)
$ PLUGINS=data-tables-api,echarts-api,prism-api bash local-test.sh
```

Pull request includes the following changes:

-  b01894e3c6b362e53343b34317606021d0694281 Revert #2678
-  e9d6e5bdad2141f18ae01f6cce00e63affe0eb77 Revert #2677
-  8f6657eddbdbb8431839340e396824580aecb4d0 Revert #2674
-  b3bf3a3154f03132cf178d11883619672deaa0c1 Exclude dependabot checks for reverted versions

The message in the [console output](https://ci.jenkins.io/job/Tools/job/bom/job/PR-2679/1/pipeline-console/?selected-node=284) is:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.1:test (default-cli) on project data-tables-api: Execution default-cli of goal org.apache.maven.plugins:maven-surefire-plugin:3.2.1:test failed: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests: ClassSelector [className = 'io.jenkins.plugins.datatables.TableModelTest'] resolution failed: 'java.util.stream.Stream org.junit.platform.commons.support.ReflectionSupport.streamNestedClasses(java.lang.Class, java.util.function.Predicate)' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.1:test (default-cli) on project data-tables-api: Execution default-cli of goal org.apache.maven.plugins:maven-surefire-plugin:3.2.1:test failed: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
```

That message is preceded by upper bounds dependency messages in the compilation:

```
[INFO] Require upper bound dependencies error for org.junit.platform:junit-platform-engine:1.10.0 [test] paths to dependency are:
+-io.jenkins.plugins:data-tables-api:1.13.8-1
  +-org.junit.jupiter:junit-jupiter-engine:5.10.0 [test]
    +-org.junit.platform:junit-platform-engine:1.10.0 [test] (managed) <-- org.junit.platform:junit-platform-engine:1.10.0 [test]
and
+-io.jenkins.plugins:data-tables-api:1.13.8-1
  +-org.junit.vintage:junit-vintage-engine:5.10.0 [test]
    +-org.junit.platform:junit-platform-engine:1.10.0 [test] (managed) <-- org.junit.platform:junit-platform-engine:1.10.0 [test]
and
+-io.jenkins.plugins:data-tables-api:1.13.8-1
  +-org.junit.platform:junit-platform-launcher:1.10.0 [test]
    +-org.junit.platform:junit-platform-engine:1.10.0 [test] (managed) <-- org.junit.platform:junit-platform-engine:1.10.0 [test]
and
+-io.jenkins.plugins:data-tables-api:1.13.8-1
  +-com.tngtech.archunit:archunit-junit5:1.2.0 [test]
    +-com.tngtech.archunit:archunit-junit5-engine:1.2.0 [test]
      +-com.tngtech.archunit:archunit-junit5-engine-api:1.2.0 [test]
        +-org.junit.platform:junit-platform-engine:1.10.0 [test] (managed) <-- org.junit.platform:junit-platform-engine:1.10.1 [test]
[INFO] for org.junit.platform:junit-platform-engine, upper bounds forces an upgrade from 1.10.0 to 1.10.1
```

I'm not sure why the test detection is failing for these plugins.  Needs help from @uhafner and probably from @basil to improve my understanding.

### Testing done

Confirmed that `PLUGINS=data-tables-api,echarts-api,prism-api bash local-test.sh` fails on the master branch unless these changes are made.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by uhafner** [comment]
All of these plugin changes require the latest Jenkins LTS 2.426.1. Maybe this is the problem? I think I need to pin the old versions in bom-2.414.x.

**Comment by basil** [comment]
`analysis-pom` is (incorrectly) pulling in a version of ArchUnit with a `requireUpperBounds` error, which `analysis-pom` has (also incorrectly) downgraded from an error to a warning in https://github.com/jenkinsci/analysis-pom-plugin/blob/66a5b3bbe81aba476e9b25d22494df9babe644b5/pom.xml#L173-L188. Since PCT will automatically resolve `requireUpperBoundDeps` errors by choosing the newer version, and since the newer version is not ABI-compatible with the older version, the issue occurs.

Can be worked around in BOM with e.g.

```bash
index 83b6f1f3..607e984e 100755
--- a/pct.sh
+++ b/pct.sh
@@ -19,6 +19,28 @@ if ! [[ $PLUGINS =~ blueocean || $PLUGINS =~ pipeline-maven ]]; then
        #
        PCT_D_ARGS+='-DforkCount=.75C '
 fi
+if [[ $PLUGINS =~ data-tables-api || $PLUGINS =~ echarts-api || $PLUGINS =~ prism-api ]]; then
+       #
+       # These plugins use a version of ArchUnit which triggers a
+       # requireUpperBoundDeps error with JUnit 5:
+       #
+       # +-io.jenkins.plugins:data-tables-api:1.13.8-1
+       # +-com.tngtech.archunit:archunit-junit5:1.2.0 [test]
+       # +-com.tngtech.archunit:archunit-junit5-engine:1.2.0 [test]
+       # +-com.tngtech.archunit:archunit-junit5-engine-api:1.2.0 [test]
+       # +-org.junit.platform:junit-platform-engine:1.10.0 [test] (managed)
+       #   <-- org.junit.platform:junit-platform-engine:1.10.1 [test]
+       #
+       # Since PCT will automatically resolve requireUpperBoundDeps errors by
+       # choosing the newer version, and since the newer version is not
+       # ABI-compatible with the older version, exclude this package from PCT's
+       # requireUpperBoundDeps resolution.
+       #
+       # When these plugins are fixed to not trigger a requireUpperBoundDeps
+       # error, this code should be removed.
+       #
+       PCT_D_ARGS+='-DupperBoundsExcludes=org.junit.platform:junit-platform-commons '
+fi
 
 exec java \
        -jar target/pct.jar \
```

but if this workaround is adopted, an issue should first be filed against `analysis-pom` to both (a) correct the underlying `requireUpperBounds` error and (b) stop treating `requireUpperBounds` as a warning instead of an error so that problems like this are not introduced in the future.

**Comment by basil** [comment]
>  Needs help […] probably from @basil

As far as I can tell, I did not introduce this issue. I can see a reason to ping @jenkinsci/bom-developers as a group, but I cannot see a reason to ping me as an individual.

**Comment by MarkEWaite** [comment]
> As far as I can tell, I did not introduce this issue. I can see a reason to ping @jenkinsci/bom-developers as a group, but I cannot see a reason to ping me as an individual.

Good point.  I pinged you because I thought you would be able to help based on past experience rather than asking the larger group for help.  I'll use the larger group in the future when my skills gaps need help.

**Comment by MarkEWaite** [comment]
Resolved by changes from @bitwiseman .  Thanks very much!

**Comment by MarkEWaite** [comment]
I've created [JENKINS-72392](https://issues.jenkins.io/browse/JENKINS-72392) to track the fix in the analysis-pom

**Pull request closed without merging**
