### PR TITLE
test: test against RC build 2.462.3

### PR DESCRIPTION
**Pull request by krisstern**
## Test against RC build of 2.462.3
Only for testing. Please do not merge.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by krisstern** [comment]
🟢 All tests passed

**Comment by MarkEWaite** [comment]
@krisstern by default, pull requests to this repository run a very few operations.  I've added the `full-test` label and reopened the pull request so that the full set of tests will be run with the pre-release.

**Comment by krisstern** [comment]
Hey @MarkEWaite, thanks for reopening the PR and adding the `full-test` label for me. I do remember it but I don't think I have permissions to add a label to it, or I do not know the GitHub command for it. Would it be possible for me to have write access to this repo moving forward, or if there is a command for it for you to teach me how to do it?

**Comment by MarkEWaite** [comment]
> Hey @MarkEWaite, thanks for reopening the PR and adding the `full-test` label for me. I do remember it but I don't think I have permissions to add a label to it, or I do not know the GitHub command for it. Would it be possible for me to have write access to this repo moving forward, or if there is a command for it for you to teach me how to do it?

We'd love to have you as a maintainer of the plugin bill of materials if you have capacity.  If you don't feel like you have capacity to be a plugin BOM maintainer, then you can use the technique described in the [README](https://github.com/jenkinsci/bom/blob/master/README.md#pct):

> To minimize cloud resources, PCT is not run at all by default on pull requests, only some basic sanity checks. Add the label full-test to run PCT in a PR. If you lack triage permission and so cannot add this label, then you may instead
> 
> echo 'TODO delete me' > full-test
> git add full-test
> git commit -m 'Run full tests'
> while keeping the PR in draft until tests pass and this file can be deleted.

**Comment by krisstern** [comment]
Hi @MarkEWaite,

Sure, I would love to be a maintainer of `bom`.
Does the checks look alright with you? I see we have 1 check errored and 2 checks failed.

**Comment by MarkEWaite** [comment]
> Sure, I would love to be a maintainer of `bom`. 

> Does the checks look alright with you? I see we have 1 check errored and 2 checks failed.

The failure was infrastructure related.  It reported:

```
06:38:50  [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-npm (install node and npm) on project data-tables-api: Could not download Node.js: Could not download https://nodejs.org/dist/v20.13.1/node-v20.13.1-linux-x64.tar.gz: Premature end of Content-Length delimited message body (expected: 46,721,240; received: 2,711,552) -> [Help 1]
06:38:50  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-npm (install node and npm) on project data-tables-api: Could not download Node.js: Could not download https://nodejs.org/dist/v20.13.1/node-v20.13.1-linux-x64.tar.gz
```

The other failing checks are a result of that infrastructure issue.

We could consider adding NodeJS download caching like we have for Maven artifacts, but the failure is rare and there are other infra improvements that are more valuable for now.

**Pull request closed without merging**
