### PR TITLE
Add `docker-commons` to the managed set

### LINKED ISSUE #2096: Add Docker Commons to the managed set
### What feature do you want to see added?

This is an API plugin and it is widely deployed, making it a perfect candidate for inclusion in the managed set.

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Add docker-commons to managed set

- Add docker-commons to managed set

Fixes #2096

### Testing done

Rely on full-test

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Tests in the docker-commons plugin need to be adapted to the plugin BOM test environment.  They assume access to the docker socket and I don't think that we want to require that in the plugin BOM test environment.  Will need changes to the tests in the docker-commons plugin to adapt to the plugin BOM test environment.

**Comment by MarkEWaite** [comment]
https://github.com/jenkinsci/docker-commons-plugin/pull/138 proposes the test change that should allow the test to run in the plugin BOM.

**Comment by MarkEWaite** [comment]
The release of docker-commons 434.xxx resolves the test failures I'd seen earlier.  Unfortunately, Jenkins 2.413 shows a test failure on DockerServerCredentialsTest.configRoundTripUpdateCertificates that does not happen with Jenkins 2.412 and earlier.  I'll do some further investigation to understand the change between Jenkins 2.412 and 2.413.  Since we're about to choose an LTS baseline, this is a very good time to detect that type of change.

**Comment by MarkEWaite** [comment]
I've submitted a docker-commons pull request to adapt the test for Jenkins 2.413 and newer.  The pull request is

* https://github.com/jenkinsci/docker-commons-plugin/pull/140

I've also asked a question in the Jenkins core pull request that made the change, just in case I've not understood something important:

* https://github.com/jenkinsci/jenkins/pull/8179

**Review by jglick — APPROVED** [review]

**Pull request merged**
