### PR TITLE
Update versions after 2023-01-24 security release

### PR DESCRIPTION
**Pull request by Kevin-CB**
https://www.jenkins.io/security/advisory/2023-01-24/

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by MarkEWaite** [comment]
@jglick or @timja should pull requests that update a dependency for a security vulnerability be labeled so that they will generate a release of the BOM when merged?  That seems like the best approach to me, but I'm unsure if there are reasons we would not release a new BOM version when this merges.

**Review by daniel-beck — APPROVED** [review]
🤷

**Comment by jglick** [comment]
> should pull requests that update a dependency for a security vulnerability be labeled so that they will generate a release of the BOM when merged?

They can be, though there is not often any particular reason they should merit a release (such as new APIs, or incompatibilities likely to affect integration tests).

**Pull request merged**
