### PR TITLE
Honor a `full-test` marker file in addition to label

### LINKED ISSUE #2151: Allow non-maintainers to run a full test
As seen in https://github.com/jenkinsci/bom/pull/2146, there is no way for contributors who are not members of @jenkinsci/bom-developers to run a full test, which unnecessarily increases the barrier to entry for contributions.

### PR DESCRIPTION
**Pull request by jglick**
Fixes #2151. (I hope; untested.)

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
If we can get a release of the pipeline model definition plugins today, I can use that as a test case for a draft pull request using this technique

**Comment by jglick** [comment]
Perfect.

(BTW we could grant various people triage permission so this is necessary less often, I think.)

**Comment by timja** [comment]
I added a few teams with triage

**Comment by MarkEWaite** [comment]
I am using this facility as part of the pull request:

* #2171

**Pull request merged**
