### PR TITLE
Add Pipeline Graph View to the managed set

### LINKED ISSUE #3136: Add Pipeline Graph View to the managed set
This plugin has over 10,000 installations and is being recommended as the replacement for Blue Ocean, so we ought to do compatibility testing on it regularly.

### PR DESCRIPTION
**Pull request by alecharp**
NOTE: Not adding weekly test label here now because of known failures.

This pull request adds Pipeline Graph View plugin on the managed set.

Fixes #3136

### Testing done

I ran 

```
PLUGINS=pipeline-graph-view bash local-test.sh
```

It has 2 tests in error in the `2.455` (weekly) line, which I can reproduce on the plugin directly (not related to PCT).
Working on those now.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by alecharp** [comment]
The two tests failing are: 
- `PipelineStepApiLegacyTest#getAllStepsReturnsStepsForComplexParallelBranches`
- `PipelineStepApiTest#getAllStepsReturnsStepsForComplexParallelBranches`

Both are now failing because of an additional step when the pipeline defined by https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/main/src/test/resources/io/jenkins/plugins/pipelinegraphview/utils/complexParallelSmokes.jenkinsfile. The additional step is making mention of `Get contextual object from internal APIs`.

**Comment by alecharp** [comment]
The tests are failing as soon as the fix from https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/700 is integrated.

**Comment by basil** [comment]
Since the fix in https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/392 will apply only to 2.440.x, I recommend testing this PR with `full-test` rather than `weekly-test`.

**Comment by alecharp** [comment]
With latest commit, the tests are not failing locally anymore. Testing with CI.

**Comment by alecharp** [comment]
5 tests in `display-url-api` plugin are not passing due to the addition of the `pipeline-graph-view` plugin here. I can reproduce those failures locally in BOM so I'm looking to find what is wrong.

**Comment by alecharp** [comment]
The failures are due to `DisplayURLProvider` urls being overwritten by `pipeline-graph-view` implementation when the `display-url-api` tests are expecting to find a custom implementation url being used.

**Comment by alecharp** [comment]
Here is the testing I've been doing to resolve the problem:

- updating parent pom, `jenkins.version` and bom on `display-url-api` plugin
- adding `pipeline-graph-view` plugin as a test dependency to `display-url-api` plugin (creates a cycling dependency but for test purpose it works
- running the test class `ActionRedirectExtendedTest` in `display-url-api` plugin
- in debug mode, breaking in the first statement of the first test, we can see:
    * `DisplayURLProvider#all()` returns a list of 4 implementations
    * the code path in `DisplayURLDecorator#decorate` is the same for both configuration (with and without the plugin)
    * when logging the headers in the tests (adding `.log().headers()`), we can see that both are resolved using the `AbstractDisplayAction#doRedirect`

I think the problem is that in `DisplayURLProvider#getPreferredProvider`, we are streaming in all the implementation of `DisplayURLProvider`. The implementation in `pipeline-graph-view` plugin is the first in the list, because of the `ordinal` and https://github.com/jenkinsci/display-url-api-plugin/blob/d3e2e182cdfb9919b122813c827be9d6e929685e/src/main/java/org/jenkinsci/plugins/displayurlapi/DisplayURLProvider.java#L221-L223 is returning that implementation when the test in the plugin expect https://github.com/jenkinsci/display-url-api-plugin/blob/d3e2e182cdfb9919b122813c827be9d6e929685e/src/test/java/org/jenkinsci/plugins/displayurlapi/actions/ActionRedirectExtendedTest.java#L101 to be the first implementation.

The `TestExtension` has no was to get an ordinal. We could change the test to configure the preferred implementation to make sure it's using the test extension.

**Comment by alecharp** [comment]
I might have a patch for the `display-url-api` plugin but I need to confirmed that it's not reducing the code coverage.

**Comment by alecharp** [comment]
I opened https://github.com/jenkinsci/display-url-api-plugin/pull/212 for review.

**Comment by alecharp** [comment]
I validated the content of https://github.com/jenkinsci/display-url-api-plugin/pull/212 by adding `--local-checkout-dir` for `display-url-api` in `pct.sh` and running `local-test.sh` script with `PLUGINS` set to `display-url-api` locally. All test passed.

**Comment by alecharp** [comment]
Once #3144 is merged, we can update this pull request and add the `full-test` label again to validate it.

**Review by basil — APPROVED** [review]
Thank you very much!

**Comment by alecharp** [comment]
I'm glad I could help.

**Comment by basil** [comment]
Still failing on the main branch pending https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/394.

**Comment by basil** [comment]
If perchance anyone happens to be awake in the next few hours and interested in helping, it would be great to take advantage of time zones to merge and release the above and restart a build of https://ci.jenkins.io/job/Tools/job/bom/job/master/ which will take several hours.

**Comment by basil** [comment]
Specifically the test was relying on the branch being named something other than `master`, which was true for https://github.com/jenkinsci/pipeline-graph-view-plugin where the branch is named `main` and was also true for https://github.com/jenkinsci/bom/pull/3137 where the branch was named PR-something-or-other, but not true for https://github.com/jenkinsci/bom where the branch is actually named `master`

**Comment by MarkEWaite** [comment]
I've started the release build on ci.jenkins.io and set the branch protection to lock the master branch.  Will watch for the completion of the release.

**Comment by alecharp** [comment]
it seems that the last build was still in error. I'm trying to load the build logs from https://ci.jenkins.io/job/Tools/job/bom/job/master/2720/pipeline-console/ but it's not showing anything.

**Pull request merged**
