### PR TITLE
Flaky CI builds

### PR DESCRIPTION
**Pull request by jglick**
From #192, #208, and `master`.

### CODE REVIEW

**Comment by basil** [comment]
PRs like this that consume an unmerged and/or unreleased upstream change need to remain in draft state until the upstream change is merged and released.

**Comment by jglick** [comment]
Referring to https://github.com/jenkinsci/plugin-compat-tester/pull/228? Yes in general. At least as of https://github.com/jenkinsci/plugin-compat-tester/pull/255 the unreleased upstream change is easier to identify.

For now we are still stuck on https://github.com/jenkinsci/plugin-compat-tester/pull/345 since none of us has had time to work on a proper supportable patch or even make the current patches be activated by some sort of experimental flag. https://github.com/jenkinsci/bom/issues/657

**Comment by basil** [comment]
#657 could have been avoided had we refrained from consuming an unmerged and/or unreleased upstream change in a non-draft PR.

**Comment by jglick** [comment]
Yes, it could; we prioritized getting `bom` builds working reliably and handling ongoing plugin releases.

**Pull request merged**
