### PR TITLE
Update plugins in 2023-02-15 security advisory

### PR DESCRIPTION
**Pull request by daniel-beck**
https://www.jenkins.io/security/advisory/2023-02-15/

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by jglick** [comment]
Also in #1761, #1762, #1763.

**Comment by daniel-beck** [comment]
@jglick We started doing this because you requested it in https://github.com/jenkinsci/bom/pull/1496#pullrequestreview-1153880461.

**Comment by jglick** [comment]
Heh, completely forgot about that. In that case it was important to update a set of plugins together, though not because they were part of a security update per se.

Not a _problem_ to do these updates, especially if you already have a process for it. Just FYI that in the typical case that they are unrelated updates released on the same day, there is no particular need to bump them manually, or to do so in an atomic PR.

**Pull request merged**
