### PR TITLE
Test jenkinsci/maven-plugin#345

### PR DESCRIPTION
**Pull request by yaroslavafenkin**
https://github.com/jenkinsci/maven-plugin/pull/345

### CODE REVIEW

**Comment by darinpope** [comment]
@yaroslavafenkin don't forget to add the `weekly-test` label

**Comment by yaroslavafenkin** [comment]
> @yaroslavafenkin don't forget to add the `weekly-test` label

I lack permissions to do that directly via UI. Is there a bot for that?

**Comment by MarkEWaite** [comment]
> > @yaroslavafenkin don't forget to add the `weekly-test` label
> 
> I lack permissions to do that directly via UI. Is there a bot for that?

Good point.  There's a [solution](https://github.com/jenkinsci/bom/blob/master/CONTRIBUTING.md#pct) for that:

> To minimize cloud resources, PCT is not run at all by default on pull requests, only some basic sanity checks. Add the label full-test to run PCT in a PR. If you lack triage permission and so cannot add this label, then you may instead
> 
> echo 'TODO delete me' > full-test
> git add full-test
> git commit -m 'Run full tests'
> while keeping the PR in draft until tests pass and this file can be deleted.
> 
> Similarly, the weekly-test label (or marker file) can be used to run tests on weekly releases in isolation.

**Comment by yaroslavafenkin** [comment]
> > > @yaroslavafenkin don't forget to add the `weekly-test` label
> > 
> > 
> > I lack permissions to do that directly via UI. Is there a bot for that?
> 
> Good point. There's a [solution](https://github.com/jenkinsci/bom/blob/master/CONTRIBUTING.md#pct) for that:
> 
> > To minimize cloud resources, PCT is not run at all by default on pull requests, only some basic sanity checks. Add the label full-test to run PCT in a PR. If you lack triage permission and so cannot add this label, then you may instead
> > echo 'TODO delete me' > full-test
> > git add full-test
> > git commit -m 'Run full tests'
> > while keeping the PR in draft until tests pass and this file can be deleted.
> > Similarly, the weekly-test label (or marker file) can be used to run tests on weekly releases in isolation.

Great to know, thanks for sharing. I'll use that in the future.

**Comment by basil** [comment]
https://ci.jenkins.io/job/Tools/job/bom/job/PR-3718/3/ passed

**Pull request closed without merging**
