### PR TITLE
Use a released version of maven-hpi-plugin

### PR DESCRIPTION
**Pull request by amuniz**
This is using an rc coming from
https://github.com/jenkinsci/maven-hpi-plugin/pull/464 which fails locally when there are no github credentials.

If https://github.com/jenkinsci/maven-hpi-plugin/pull/464 is really needed it should be released (probably behind a flag).

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by amuniz** [comment]
Asking @basil for a review, as author of https://github.com/jenkinsci/maven-hpi-plugin/pull/464

**Comment by basil** [comment]
> which fails locally when there are no github credentials

It is guarded under the CI environment variable which should not be set when running locally

**Comment by jglick** [comment]
It is not about GH credentials but about including `!incrementals` in `<mirrorOf>` in `settings.xml`, if that was the issue.

From a quick glance at https://github.com/jenkinsci/maven-hpi-plugin/pull/464 it seems it could be released as is perhaps with just a note that the new property is experimental and could be removed without notice?

**Comment by basil** [comment]
But the CI environment variable should never be set locally, so that line of code should never be executed locally

**Comment by amuniz** [comment]
> But the CI environment variable should never be set locally

Well, I wanted to test a modification in the code which is supposed to run in CI, so I had to enable the CI flag.
Anyways, I don't think using an incremental release of the plugin based on an old revision is a good idea.

**Comment by basil** [comment]
OK, even in that case, you must have something weird about your Maven mirror configuration, as it works fine for me locally.

**Review by basil — CHANGES_REQUESTED** [review]
Requesting changes for the following reason: breaks CI build

In the most extreme case, I would vote for this code to be deleted rather than released, as this experiment has outlived its usefulness.

**Comment by jglick** [comment]
I have no knowledge of the status of the Launchable integration, but I guess

> I would vote for this code to be deleted rather than released, as this experiment has outlived its usefulness.

would mean (too big to “suggest changes”) deleting https://github.com/jenkinsci/bom/blob/a25bab9f95345e429e8ab2d7b0a692bf1ef9a46e/prep.sh#L33 https://github.com/jenkinsci/bom/blob/a25bab9f95345e429e8ab2d7b0a692bf1ef9a46e/prep.sh#L41-L42 amending https://github.com/jenkinsci/bom/blob/a25bab9f95345e429e8ab2d7b0a692bf1ef9a46e/prep.sh#L46 deleting https://github.com/jenkinsci/bom/blob/53343baba850d016b9c39cd3b6b3d10c2a576d48/Jenkinsfile#L70-L79 https://github.com/jenkinsci/bom/blob/53343baba850d016b9c39cd3b6b3d10c2a576d48/Jenkinsfile#L109-L114 right?

**Comment by basil** [comment]
> Well, I wanted to test a modification in the code which is supposed to run in CI, so I had to enable the CI flag.

What is this all about?

**Comment by basil** [comment]
Unresponsive.

**Pull request closed without merging**
