### PR TITLE
feat: Add ionicons-api-plugin to BOM

### PR DESCRIPTION
**Pull request by NotMyFault**

### CODE REVIEW

**Comment by NotMyFault** [comment]
> [2022-08-22T17:24:25.186Z] [ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.32:validate-hpi (default-validate-hpi) on project sample: Dependency io.jenkins.plugins:ionicons-api:jar:15.vc8f8c4502de5 requires Jenkins 2.346.1 or higher. -> [Help 1]

The sample plugin uses the latest weekly, why would it fail on dependencies bound to older versions?

**Comment by jetersen** [comment]
@NotMyFault because it is build against each line in the preparation step: https://ci.jenkins.io/blue/organizations/jenkins/Tools%2Fbom/detail/PR-1414/1/pipeline#step-23-log-1117

**Comment by jetersen** [comment]
Since this is such a new plugin you cannot add it unless you remove it from older boms which I don't think is possible.

Perhaps you need to create a tombstone version for older versions?

**Comment by NotMyFault** [comment]
The oldest weekly that ships symbols is 2.235, but 2.346.1 was the first LTS version that contained plugin support.

Guess we will need to leave it off BOM for a few LTS releases 😢

**Comment by jetersen** [comment]
You could great a tombstone version that targets 3.319 or ya we would need to wait till we drop `2.332.x`

**Comment by NotMyFault** [comment]
Yah, we can wait for now, I guess. But thanks for the pointer with 2.332.x 👍🏻

**Pull request closed without merging**
