### PR TITLE
Retire 2.235

### PR DESCRIPTION
**Pull request by timja**
Unblocks https://github.com/jenkinsci/bom/pull/571

We have a very large number of lines right now

### CODE REVIEW

**Comment by basil** [comment]
Per `README.md` the waiting period is 400 days, and it's only been 348 days since the release of 2.235.5, but it's probably close enough. I don't feel strongly either way. It might be good to first do a final BOM release for the 2.235.x line that includes a version of the Git plugin that doesn't have a problematic plugin parent POM of 4.20, 4.21, or 4.22 (when such a version of the Git plugin is released).

**Comment by timja** [comment]
> Per `README.md` the waiting period is 400 days, and it's only been 348 days since the release of 2.235.5, but it's probably close enough. I don't feel strongly either way. It might be good to first do a final BOM release for the 2.235.x line that includes a version of the Git plugin that doesn't have a problematic plugin parent POM of 4.20, 4.21, or 4.22 (when such a version of the Git plugin is released).

We generally drop when required as well, to unblock the modern UI plugin updates we need to drop a line.

**Comment by basil** [comment]
> If the master build passes a release should happen

That release of the 2.235 BOM line will have `git-plugin` 4.8.1, which has the problematic parent POM 4.21. I'd personally like to see @MarkEWaite release a new version of `git-plugin` with plugin parent POM 4.24 or later, BOM pulling in that version, and releasing one more 2.235 BOM with an updated Git plugin before we kill the 2.235 line.

**Comment by basil** [comment]
> Unless it's causing an issue I wouldn't wait

I would wait, but I have no strong preference either way. Non-blocking.

**Comment by timja** [comment]
> > If the master build passes a release should happen
> 
> That release of the 2.235 BOM line will have `git-plugin` 4.8.1, which has the problematic parent POM 4.21. I'd personally like to see @MarkEWaite release a new version of `git-plugin` with plugin parent POM 4.24 or later, BOM pulling in that version, and releasing one more 2.235 BOM with an updated Git plugin before we kill the 2.235 line.

If @MarkEWaite has plans to do it soon then sure, otherwise I'd like to get the modern ui plugins sorted :)

**Comment by MarkEWaite** [comment]
I don't object to performing an immediate release of git plugin and git client plugin.  The current releases of both plugins are based on plugin pom 4.21.  However, I've not seen any reports of git plugin or git client plugin issues related to plugin pom 4.21.  I've seen the reports related to pipeline model plugins, but none on git plugin or git client plugin.

Did I miss a discussion somewhere?

**Comment by MarkEWaite** [comment]
> > If the master build passes a release should happen
> 
> That release of the 2.235 BOM line will have `git-plugin` 4.8.1, which has the problematic parent POM 4.21. I'd personally like to see @MarkEWaite release a new version of `git-plugin` with plugin parent POM 4.24 or later, BOM pulling in that version, and releasing one more 2.235 BOM with an updated Git plugin before we kill the 2.235 line.

I'm not precisely sure what is meant by "2.235 BOM", but if it means a bill of materials that describes Jenkins plugins that are known to work with Jenkins 2.235.x, then that BOM won't include git plugin 4.8.1 because git plugin 4.8.1 requires Jenkins 2.263.1 or newer.  The last version of the git plugin to support Jenkins 2.235.x was 4.6.0, released in Feb 2021.

**Comment by basil** [comment]
You didn't, Mark. There are no reported problems, but I'm just being paranoid. That's why my preference is non-blocking. :-)

**Comment by basil** [comment]
> I'm not precisely sure what is meant by "2.235 BOM", but if it means a bill of materials that describes Jenkins plugins that are known to work with Jenkins 2.235.x, then that BOM won't include git plugin 4.8.1 because git plugin 4.8.1 requires Jenkins 2.263.1 or newer. The last version of the git plugin to support Jenkins 2.235.x was 4.6.0, released in Feb 2021.

Oh right! So my concern is moot. Sorry for the false alarm.

**Review by basil — APPROVED** [review]

**Comment by MarkEWaite** [comment]
> You didn't, Mark. There are no reported problems, but I'm just being paranoid. That's why my preference is non-blocking. :-)

I'm fully in favor of paranoia when it comes to the git plugin and the git client plugin.  I agree that it would be more comfortable to have a release based on plugin pom 4.24.  I've not seen any reports of issues related to plugin pom 4.24, so I assume it is safe to release based on that pom.

**Pull request merged**
