### PR TITLE
Adds Office-365-Connector plugin

### PR DESCRIPTION
**Pull request by damianszczepanik**
### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by alecharp** [comment]
Hello @damianszczepanik. Thank you for your pull request. 

I'm wondering if you could let us know if you run the PCT for this plugin on your end, and if so what was the result of it?

I see that the plugin is installed on about 6% of the known controllers and it has no dependent plugin. I'm wondering if this addition wouldn't be just increasing the cost of the build. Could you help us see the requirement to have this plugin in the bill of material? Thanks.

**Comment by jglick** [comment]
[general recommendations](https://github.com/jenkinsci/bom/blob/master/README.md#when-to-add-a-new-plugin) FYI

**Comment by alecharp** [comment]
I'm aware of that section. I agree that 6% is 18533 users so that it can qualify to the rule of

> * In the list of plugins with more than 10,000 (or 1,000) users

But still it seems low. Anyway, it would be nice to make sure that the PCT were ran locally so that it's not discovered at release time and we have to revert the addition of the plugin.

**Comment by damianszczepanik** [comment]
> Hello @damianszczepanik. Thank you for your pull request.
> 
> I'm wondering if you could let us know if you run the PCT for this plugin on your end, and if so what was the result of it?
> 

Take a look at #2894 - this is the result of my local execution. I found the problem with upper case naming and I have submitted the issue. Results on Jenkins is same as on my local workstation, same test is failing. Given error stopped me so I don't know if PCT completes without issue.
Plugins runs with [JDK 11 and 17](https://github.com/jenkinsci/office-365-connector-plugin/blob/master/Jenkinsfile) but does not with 21 (test fails when executing with JDK 21) so that might be a problem for PCT.

**Comment by damianszczepanik** [comment]
> Hello @damianszczepanik. Thank you for your pull request.
> 
> Could you help us see the requirement to have this plugin in the bill of material? Thanks.

I know how annoying maintaining version is - at lest for me who has a few Jenkins plugin. I wanted to update the plugin and spend some time on this so others don't have to. If you think that effort for having this plugin in BOM is high then I'm OK with closing this pull request.

**Comment by alecharp** [comment]
Hello, we have notice that the plugin has Changelog file or any GitHub release. This means that if something new in the plugin that breaks the PCT run, we won't be able to easily detect what changed.

So far, I don't see the need to add this plugin to the BOM and I don't think it's a good idea.

**Comment by basil** [comment]
I'm all for increasing the amount of testing we do on a regular basis, but this particular plugin cannot be included in the BOM until its tests pass on Java 21.

**Pull request closed without merging**
