### PR TITLE
Init plugin compatibility test for LTS 2.414.3

### PR DESCRIPTION
**Pull request by krisstern**
### Description
To confirm the incremental produced by the backporting PR does not contain regressions.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks very much @krisstern !  I've added the `full-test` label so that all the tests will be run.  The first run did not include that label, so may not run all the tests.  May need you (or me) to re-run the job to run all tests

**Comment by krisstern** [comment]
> Thanks very much @krisstern ! I've added the `full-test` label so that all the tests will be run. The first run did not include that label, so may not run all the tests. May need you (or me) to re-run the job to run all tests

You are welcome @MarkEWaite! I will remember to add the `full-test` label moving forward.

**Comment by MarkEWaite** [comment]
@krisstern I'm closing this pull request.  The job completed with only one failure out of 610 test configurations.  The one failure was due to a transient infrastructure issue with the artifact caching proxy not responding to a request.  I think we're "good to go" with this validation run.

**Comment by krisstern** [comment]
Sure @MarkEWaite

**Pull request closed without merging**
