### PR TITLE
skip maven release plugin as well on sample plugin

### PR DESCRIPTION
**Pull request by jetersen**
this should fix the need for reincrementalify this sample plugin. We don't really care what version the sample plugin is or do we?

### CODE REVIEW

**Comment by jetersen** [comment]
NVM this is already added... Need option to skip profile 🤔

**Comment by jetersen** [comment]
@jglick why not remove the sample-plugin module in the pom.xml at the root and than call mvn -f sample-plugin/pom.xml directly?

**Comment by jglick** [comment]
> remove the sample-plugin module in the pom.xml at the root

It is used for testing.

**Review by jglick — CHANGES_REQUESTED** [review]
https://github.com/jenkinsci/bom/blob/04d722e73677135e7480d973903a7f8459ac99b0/sample-plugin/pom.xml#L303-L316 :grin:

**Comment by jglick** [comment]
AFAIK the only fix for this that does not involve patching `incrementals-tools` is #496, which we would like to do anyway.

**Comment by jetersen** [comment]
Hmmm I think the easier fix is again to exclude the module, and when you need to test you use `mvn -f sample-plugin`

**Comment by jglick** [comment]
> when you need to test

This would mess up various workflows both local and in CI.

The only real problem right now is that you need to remember to type one command after releasing, as in https://github.com/jenkinsci/bom/#releasing, but it would be nicer to be able to use JEP-229 to release remotely.

**Pull request closed without merging**
